[package]
name = "nucleus-http"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
pretty_env_logger = "0.4.0"

[[example]]
name = "simple"
